micronaut:
  application:
    name: libreshare
  server:
    port: 9999
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB
    cors:
      enabled: true
  router:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
      - pattern: /swagger/*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/*
        http-method: GET
        access:
          - isAnonymous()
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/libreshare
    driverClassName: org.postgresql.Driver
    username: libreshare
    password: 123456aA
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
