micronaut:
  application:
    name: libreshare
  server:
    port: ${server.port}
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${security.secret}
              jws-algorithm: HS512
    endpoints:
      login:
        enabled: true
      logout:
        enabled: false
      keys:
        enabled: false
    intercept-url-map:
      - pattern: /swagger/*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/*
        http-method: GET
        access:
          - isAnonymous()
datasources:
  default:
    url: jdbc:postgresql://${database.hostname}:${database.port}/${database.database}
    driverClassName: org.postgresql.Driver
    username: ${database.username}
    password: ${database.password}
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
