apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: libreshare-base
      context: .
      jib:
        project: web
deploy:
  kubectl:
    manifests:
      - packages/kubernetes/*
