libreshare:
  web:
    security:
      secret: wh2klh4re38dirlk45twkqfdhe3h2whkskh3ehkrhdkhedhkshs3shkhrehkshk3shkhkabo6hdhh4hhe9psaüp
    database:
      hostname: localhost
      port: 5432
      name: libreshare
      username: libreshare
      password: 123456aA
