name: Libreshare CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2
      -   name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
      -   name: Fix Gradle file permissions
          run: chmod +x gradlew
      -   name: Build the project
          run: ./gradlew build
